addons:
  chrome: stable

before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
# command to install dependencies
install:
   - docker pull katalonstudio/katalon
# command to run tests

before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  
script:
  - sh runchrome.sh